---
description: "Run all Huff test files in the repository"
inputs:
  test-extension:
    default: .t.huff
    description: "The File extension of your Huff test files"
    required: false
  with-forge-tests:
    default: false
    required: false
name: "Huff Tests"
runs:
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: "Installing Huff"
      uses: huff-language/huff-toolchain@v2
      with:
        version: nightly

    - if: "${{ inputs.with-forge-tests }}"
      name: "Installing foundry"
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - run: 'echo "${{ github.action_path }}" >> $GITHUB_PATH'
      shell: bash

    - if: "${{ inputs.with-forge-tests }}"
      name: "Running Forge tests"
      run: "forge test -vvv"
      shell: bash

    - name: "Running Huff tests"
      run: "bash hufftests.sh ${{ inputs.test-extension }}"
      shell: bash
  using: composite
